{% set version = "1.6.28" %}

package:
  name: libpng
  version: {{ version }}

source:
  fn: libpng-{{ version }}.tar.gz
  url: http://download.sourceforge.net/libpng/libpng-{{ version }}.tar.gz
  md5: 897ccec1ebfb0922e83c2bfaa1be8748

build:
  number: 0
  skip: True  # [win and py>35]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - libtool  # [not win]
    - automake  # [not win]
    - zlib 1.2.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - zlib 1.2.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  commands:
    - test -f ${PREFIX}/lib/libpng.a  # [not win]
    - test -f ${PREFIX}/lib/libpng.so  # [linux]
    - test -f ${PREFIX}/lib/libpng.dylib  # [osx]
    - libpng-config --version  # [not win]
    - conda inspect linkages -p $PREFIX libpng  # [not win]
    - conda inspect objects -p $PREFIX libpng  # [osx]

about:
  home: http://www.libpng.org/pub/png/libpng.html
  license: zlib/libpng
  summary: 'PNG reference library.'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
